### ISSUE TITLE
registry unavailable?

### ISSUE THREAD

**Issue by symac** [uleodolter/primo-explore-devenv-docker#1]
Hello,
following the webinar yesterday where one of you introduced this docker version of primo-explore-devenv I was willing to give it a try but I have got an issue with getting the image as registry.obvsg.at/primo/frontend/primo-explore-devenv-docker does not seems to be available.

Is this because the server is private or is this just a temporary issue?

Regards,
Sylvain

**Comment by uleodolter** [comment]
Hi,

you can build a local image, i need to update the documentation and examples.   i will try to update  uleodolter/primo-explore-devenv-docker on dockerhub.

```
docker build -t primo-explore-devenv-docker
```

then copy docker-compose-example.yml to  docker-compose.yml and adjust for your needs.  e.g.:

```
version: '3'

services:

  devenv:
    image: primo-explore-devenv-docker
    environment:
      PROXY: ${PROXY}
      VIEW: ${VIEW}
      GULP_OPTIONS: ${GULP_OPTIONS}
      DEVENV_UID: ${DEVENV_UID:-1000}
      DEVENV_GID: ${DEVENV_GID:-1000}
    ports:
      - 8003:8003
      - 3001:3001
    volumes:
      - ./:/app/primo-explore-devenv/packages
      - ./:/app/primo-explore-devenv/primo-explore/custom/${VIEW}
```

in your `.env` you shoud set a few variables, e.g:

```
VIEW=MyVID
GULP_OPTIONS=--browserify --useScss
PROXY=https://your.primo.domain:443
```

the `bin/run` script shows how docker-compose is used to start the environment.  the docker-compose assumes you are work in a project path which has at least the following subdirectories:

```
img
css
html
js
```

so the best way is to clone this repo, build a local image and then create a docker-compose.yml and .env in your view project.  hope this helps
